M48
; DRILL file {KiCad 7.0.10} date Sun Jan 28 22:47:31 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-28T22:47:31+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X5.5657Y-4.3688
X5.8078Y-4.1267
T2
X6.676Y-4.2862
X6.6965Y-4.1699
M30
